version: '3'

services:
  nginx:
    restart: unless-stopped
    image: staticfloat/nginx-certbot
    container_name: ncert_s
    ports:
      - 80:80/tcp
      - 443:443/tcp
    env_file:
      - config/.envfile
    volumes:
      - ./src:/app
      - ./config/nginx:/etc/nginx/user.conf.d:ro
      - letsencrypt:/etc/letsencrypt
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "1"

volumes:
  letsencrypt:
